---
title: "Using plotly"
---


```{r message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Loading airbnb data set
```{r}
data("nyc_airbnb")
nyc_airbnb =
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |> 
  select(
    neighbourhood_group, rating, neighbourhood, room_type, price, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Scatterplot
```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating)
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Boxplots
```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Bar chart
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar"
  ) 
```


Go back to [homepage](index.html)

