---
title: "P8105 Dashboard - Safe (Grade A) Sweet Treats!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: sandstone
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec =
  rest_inspec |> 
  mutate (
    temp = latitude,
    latitude = longitude,
    longitude = temp
  ) |> 
  select(-temp) |>
  filter(
    boro == "Manhattan",
    cuisine_description %in% c("Ice Cream, Gelato, Yogurt, Ices", "Donuts", "Bakery"),
    latitude != 0
    ) 

codes_descriptions = 
  rest_inspec |> 
  select(violation_code, violation_description) |> 
  distinct() |> 
  group_by(violation_code) |> 
  ungroup()
```


Column {data-width=650}
-----------------------------------------------------------------------

### Where are the "safe" sweet treats in Manhattan?
```{r}
rest_inspec |> 
  filter(grade == "A") |> 
  mutate(
    label = str_c(dba, "\n", building, " ", street)
  ) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, color = ~cuisine_description,
    colors = c(
      "Ice Cream, Gelato, Yogurt, Ices" = "#C3B1E1", 
      "Donuts" = "#E30B5D", 
      "Bakery" = "#CDA46E"  
    ),
    text = ~label,
    type = "scatter", mode = "markers"
  ) |> 
  layout(
    title = "Sweet Treats with A Grades in Manhattan",
    xaxis = list(title = "Latitude"),
    yaxis = list(title = "Longitude")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### What are the most common violation codes for "safe" sweet treats?
```{r}
top_violations = 
  rest_inspec |>
  filter(grade == "A") |> 
  group_by(violation_code, cuisine_description) |>
  summarize(count = n()) |>
  mutate(total_violation_count = sum(count)) |>
  ungroup() |>
  filter(total_violation_count > 50) |>
  left_join(codes_descriptions, by = "violation_code") |> 
  mutate(violation_code = fct_reorder(violation_code, total_violation_count)) |> 
  arrange(desc(total_violation_count)) 

top_violations |> 
  plot_ly(
    x = ~count, y = ~violation_code, color = ~cuisine_description,
    colors = c(
      "Ice Cream, Gelato, Yogurt, Ices" = "#C3B1E1", 
      "Donuts" = "#E30B5D", 
      "Bakery" = "#CDA46E"  
    ),
    type = "bar"
  ) |> 
  layout(
    barmode = "stack",
    title = "Violation Counts by Code (> 50 total violations)",
    xaxis = list(title = "Total Violation Count"),
    yaxis = list(title = "Violation Code")
  )

top_violations |> 
  select(violation_code, violation_description) |> 
  distinct() |> 
  knitr::kable(col.names = c("Code", "Description"))
```

### What's wrong with the restaurants that have low score but a C grade?

```{r}
rest_inspec |>
  filter(grade %in% c("A", "B", "C")) |> 
  plot_ly(
    x = ~cuisine_description,
    y = ~score,
    color = ~grade, 
    colors = c(
      "A" = "#244898",  
      "B" = "#5EAD55", 
      "C" = "#E49B40"    
    ),
    type = 'box', boxpoints = "all", pointpos = 0, jitter = 0.1
  ) |>
  layout(
    title = "Inspection Score Distribution by Grade and Cuisine",
    xaxis = list(title = "Cuisine Type"),
    yaxis = list(title = "Inspection Score"),
    boxmode = "group"
  )

rest_inspec |>
  filter(grade == "C", score <= 10) |> 
  select(score, dba, violation_code, violation_description) |> 
  arrange(desc(violation_code)) |> 
  knitr::kable(col.names = c("Score", "Restaurant", "Violation Code", "Violation Description"))

```

